spring:
  liquibase:
    change-log:  classpath:/db/changelog/changelog-master.yml  # Liquibase changelog faylının yeri

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rsocket:
server:
  port: 8085